import * as pdfjs from './vendor/pdfjs/pdf.min.mjs';
pdfjs.GlobalWorkerOptions.workerSrc='./vendor/pdfjs/pdf.worker.min.mjs';
const $=s=>document.querySelector(s),source=new URLSearchParams(location.search).get('src');
let doc,zoom=1,current=1,generation=0,observer;const tasks=new Map();let drawing=Promise.resolve();
function status(){ $('#page-number').value=current;$('#prev').disabled=current<=1;$('#next').disabled=!doc||current>=doc.numPages; }
function jump(value){if(!doc)return;current=Math.max(1,Math.min(doc.numPages,Number(value)||1));document.querySelector(`[data-page="${current}"]`)?.scrollIntoView({block:'start'});status();}
async function draw(holder,token){if(token!==generation||holder.dataset.rendered||holder.dataset.visible!=='yes')return;holder.dataset.rendered='pending';const page=await doc.getPage(Number(holder.dataset.page));if(token!==generation)return;const unit=page.getViewport({scale:1});holder.style.aspectRatio=`${unit.width}/${unit.height}`;const scale=holder.clientWidth/unit.width,viewport=page.getViewport({scale}),ratio=Math.min(devicePixelRatio||1,2),canvas=document.createElement('canvas');canvas.width=Math.floor(viewport.width*ratio);canvas.height=Math.floor(viewport.height*ratio);canvas.setAttribute('aria-label',`PDF 第 ${holder.dataset.page} 页`);const context=canvas.getContext('2d');const task=page.render({canvasContext:context,viewport,transform:ratio!==1?[ratio,0,0,ratio,0,0]:null});tasks.set(holder,task);try{await task.promise;if(token!==generation)return;holder.replaceChildren(canvas);holder.dataset.rendered='done';}catch(e){if(e.name!=='RenderingCancelledException'){holder.textContent='本页渲染失败，可下载原文件查看。';}}finally{tasks.delete(holder);}}
async function layout(){const token=++generation;observer?.disconnect();for(const task of tasks.values())task.cancel();tasks.clear();const active=current;const first=await doc.getPage(1);if(token!==generation)return;const unit=first.getViewport({scale:1}),width=Math.min(Math.max(200,innerWidth-40),980)*zoom;$('#pages').replaceChildren();$('#zoom-label').textContent=Math.round(zoom*100)+'%';for(let n=1;n<=doc.numPages;n++){const holder=document.createElement('section');holder.className='pdf-page';holder.dataset.page=n;holder.style.width=width+'px';holder.style.aspectRatio=`${unit.width}/${unit.height}`;holder.style.scrollMarginTop='65px';holder.innerHTML=`<span class="placeholder">第 ${n} 页</span>`;$('#pages').append(holder);}observer=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting){entry.target.dataset.visible='yes';drawing=drawing.then(()=>draw(entry.target,token)).catch(()=>{});}else{entry.target.dataset.visible='no';if(entry.target.dataset.rendered==='done'){entry.target.replaceChildren();delete entry.target.dataset.rendered;}}}},{rootMargin:'600px 0px'});document.querySelectorAll('.pdf-page').forEach(h=>observer.observe(h));jump(active);}
try{if(!source||new URL(source,location.href).origin!==location.origin||!new URL(source,location.href).pathname.startsWith(new URL('../r/',location.href).pathname))throw Error('无效的 PDF 地址');$('#download').href=source;$('#original').href=source;doc=await pdfjs.getDocument({url:source,cMapUrl:'./vendor/pdfjs/cmaps/',cMapPacked:true,standardFontDataUrl:'./vendor/pdfjs/standard_fonts/',disableAutoFetch:true,disableStream:true,rangeChunkSize:262144,isEvalSupported:false}).promise;$('#message').hidden=true;$('#page-count').textContent='/ '+doc.numPages;$('#page-number').max=doc.numPages;await layout();status();}catch(e){$('#message').textContent='PDF 无法打开：'+e.message;}
$('#prev').onclick=()=>jump(current-1);$('#next').onclick=()=>jump(current+1);$('#page-number').onchange=e=>jump(e.target.value);$('#plus').onclick=()=>{zoom=Math.min(2.5,zoom+.25);if(doc)layout();};$('#minus').onclick=()=>{zoom=Math.max(.5,zoom-.25);if(doc)layout();};
let resizeTimer;addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(doc)layout();},180);});
addEventListener('scroll',()=>{const holders=[...document.querySelectorAll('.pdf-page')];const nearest=holders.find(h=>h.getBoundingClientRect().bottom>100);if(nearest){current=Number(nearest.dataset.page);status();}},{passive:true});
